apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  hostAliases:
  - ip: "192.168.0.200"
    hostnames:
    - "jenkins.s3t.co"
    - "tunnel.jenkins.s3t.co"
    - "nexus.s3t.co"
    - "docker-s.nexus.s3t.co"
    - "docker-r.nexus.s3t.co"
    - "docker-p.nexus.s3t.co"
    - "docker-g.nexus.s3t.co"
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources:
      requests:
        ephemeral-storage: "4Gi"
      limits:
        ephemeral-storage: "5Gi"
  volumes:
    - name: kaniko-secret
      secret:
        secretName: nexus-s3t-co-docker-config
        items:
          - key: .dockerconfigjson
            path: config.json